Algoritmo "algoritmo_decisao"
// Disciplina  : Lógica de Programação com VisualG
// Professor   : Jailson Costa dos Santos 
// Descrição   : Solicita um número, verifica se número é menor que 10, e exibe uma mensagem
// Autor(a)    : Enzo Hideaki Une
// Data atual  : 30/03/2026
Var
// Seção de Declarações das variáveis 
   numero1:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite um valor: ")
   leia(numero1)
   
   se numero1 < 10 entao
      escreval("O valor digitado é menor que 10")
   fimse

Fimalgoritmo