Algoritmo "antecessor"
// Disciplina  : Linguagem e Lógica de Programação com VisualG
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicitar um número e mostrar o antecessor
// Autor(a)    : Enzo Hideaki Une
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis 
   numero: inteiro
   antecessor: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite um número para mostrar o antecessor: ")
   leia(numero)
   
   antecessor <-  numero - 1
   
   escreva("O número antecessor é:", antecessor)

Fimalgoritmo