Algoritmo "caracteres"
// Disciplina   : Linguagem e Lógica de Programação com VisualG
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicita o nome do usuário e mostra saudações
// Autor(a)    : Enzo Hideaki Une
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis 
   nome: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite o seu nome: ")
   leia(nome)
   
   escreva("Seja bem-vindo, ", nome, "!")

Fimalgoritmo