Algoritmo "enquanto"
// Disciplina  : Lógica de Programação com VisualG
// Professor   : Jailson Costa dos Santos
// Descrição   : Exemplo de laço de repetição
// Autor(a)    : Enzo Hideaki Une
// Data atual  : 13/04/2026
Var
   // Seção de Declarações das variáveis
   contadora:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   enquanto contadora < 10 faça
      escreval("Enzo")
      contadora <- contadora + 1
   fimenquanto

Fimalgoritmo