Algoritmo "estrutura _de_repeticao"
// Disciplina  : Lógica de Programação com VisualG
// Professor   : Jailson Costa dos Santos
// Descrição   : Exemplo de Estrutura de Repetição
// Autor(a)    : Enzo Hideaki Une
// Data atual  : 01/04/2026
Var
   // Seção de Declarações das variáveis
   contador:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   enquanto contador < 10 faca
      escreval("Pão")
      contador <- contador + 1
   fimenquanto

Fimalgoritmo