Algoritmo "exemplo_para"
// Disciplina  : Lógica de Programação com VisualG
// Professor   : Jailson Costa dos Santos
// Descrição   : Laço de repetição Para
// Autor(a)    : Enzo Hideaki Une
// Data atual  : 13/04/2026
Var
   // Seção de Declarações das variáveis
   contador:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Exemplo de Repetição Para:")
   
   escreval("")
   
   para contador de 1 ate 10 passo 1 faca
      escreval(contador)
   fimpara
   
   // contador de 1 = inicialização
   // ate 10 = "condição"
   // passo 1 = incremento

Fimalgoritmo