Algoritmo "quadrado_numero_15_200"
// Disciplina  : Lógica de Programação com VisualG
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200.
// Autor(a)    : Enzo Hideaki Une
// Data atual  : 17/04/2026
Var
   // Seção de Declarações das variáveis
   contador, quadrado:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para contador de 15 ate 200 passo 1 faca
      quadrado <- contador * contador
      escreval(contador, " ^ 2 =", quadrado)
   fimpara

Fimalgoritmo