Algoritmo "repita"
// Disciplina  : Lógica de Programação com VisualG
// Professor   : Jailson Costa dos Santos
// Descrição   : Laço de repetição Repita
// Autor(a)    : Enzo Hideaki Une
// Data atual  : 13/04/2026
Var
   // Seção de Declarações das variáveis
   contador:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   repita
      escreval("Enzo")
      contador <- contador + 1
   ate contador > 9

Fimalgoritmo