Algoritmo "soma"
// Disciplina  : Linguagem e Lógica de Programação com VisualG
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicita dois números inteiros, soma e exibe o resultado
// Autor(a)    : Enzo Hideaki Une
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis 
   numero1: inteiro
   numero2: inteiro
   res: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite um número: ")
   leia(numero1)
   escreva("Digite outro número: ")
   leia(numero2)
   
   res <- numero1 + numero2
   
   escreva("O resultado da soma entre os dois números é igual a", res)

Fimalgoritmo